# Generated by Django 4.0.4 on 2022-05-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
