# Generated by Django 4.0.4 on 2022-05-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.CharField(default='/media/course_logo/index.png', max_length=255),
        ),
    ]
