# Generated by Django 4.0.4 on 2022-05-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='browser',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
